<?php
/**Generate by ASGENS
*@author Carlos Almeida  
*@date Sun May 21 16:54:11 GMT-04:00 2023  
*@time Sun May 21 16:54:11 GMT-04:00 2023  
*/
namespace Modules\administracion_\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla persona.
 *
 * Los siguientes son los campos de la tabla 'persona':
 * @property integer $id
 * @property string $nombre
 * @property string $apellidos
 * @property integer $edad
 * @property string $correo

 * Los siguientes son las relaciones de este modelo :

 **/



class Persona extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'persona';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'test';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = [];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Persona';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id',
      'nombre',
      'apellidos',
      'edad',
      'correo'
    ];



    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'nombre' =>'required|max:255',
                'apellidos' =>'required|max:255',
                'edad' =>'required',
                'correo' =>'required|max:255'
            ],
            'update'=>[
                'id' =>'required|unique:'.$this->connection.'.persona,id,'.$this->id.',id',
                'nombre' =>'required|max:255',
                'apellidos' =>'required|max:255',
                'edad' =>'required',
                'correo' =>'required|max:255'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

